
---
- name: Install Clickhouse
  hosts: clickhouse-01
  become: true
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: "clickhouse-server"
        state: restarted
  tasks:
    - name: Get clickhouse-client distrib 
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-client_{{ clickhouse_version }}_all.deb"
        dest: "{{ install_dir }}/clickhouse-client_{{ clickhouse_version }}.deb"
        mode: 0644
        force: true 

    - name: Get clickhouse-common distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
        dest: "{{ install_dir }}/clickhouse-common-static_{{ clickhouse_version }}.deb"
        mode: 0644
        force: true

    - name: Get clickhouse-server distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-server_{{ clickhouse_version }}_all.deb"
        dest: "{{ install_dir }}/clickhouse-server_{{ clickhouse_version }}.deb"
        mode: 0644
        force: true

    - name: Install clickhouse packages
      become: true
      apt:
        name: "{{ item }}"
      loop:
        - "/home/vagrant/tmp/clickhouse-common-static_{{ clickhouse_version }}.deb"
        - "{{ install_dir }}/clickhouse-server_{{ clickhouse_version }}.deb"
        - "{{ install_dir }}/clickhouse-client_{{ clickhouse_version }}.deb"

            # - /home/vagrant/.ansible/tmp/clickhouse-common-static_{{ clickhouse_version }}.deb
            # - /home/vagrant/.ansible/tmp/clickhouse-client_{{ clickhouse_version }}.deb
            # - /home/vagrant/.ansible/tmp/clickhouse-server_{{ clickhouse_version }}.deb
          # update_cache: true    
            #    with_items:

      notify: Start clickhouse service

    - name: Create database
      become: true
      command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

  tasks:
    - name: Ensure dir
      become: true
      file:
        state: directory
        path: "{{ vector_dir }}"

    - name: Download vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.2/vector-0.21.2-aarch64-unknown-linux-musl.tar.gz"
        dest: "{{ vector_dir }}/vector.tar.gz"
        mode: 0644
        force: true

    - name: Extract vector
      become: true
      unarchive:
        src: "{{ vector_dir }}/vector.tar.gz"
        dest: "{{ vector_dir }}"
        extra_opts: [--strip-components=2]
        creates: "{{ vector_dir }}/bin"

    - name: Set environment vector
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "^vector"
        line: "export PATH=$PATH:/home/vagrant/.vector/bin"

    - name: Make virtual environment
      # become: true
      shell: source "/home/vagrant/.bashrc"
      args:
        executable: /bin/bash       
    
    - name: Start vector
      command: "{{ vector_dir }}/bin/vector --config {{ vector_dir }}/config/vector.toml"
        
